## Slack Notification

global:
  resolve_timeout: 1m
  slack_api_url: 'hxtxtxpsx://hooks.slack.com/services/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'
receivers:
- name: 'slack-notificaions'
  slack_configs:
  - channel: '#devops-counsel-alertmanager-demo'
    send_resolved: true
route:
  group_interval: 5m
  group_wait: 10s
  receiver: 'slack-notificaions'
  repeat_interval: 3h


## Email Notification

alertmanagerFiles:
  alertmanager.yml: 
    global:
      resolve_timeout: 1m
      # slack_api_url: ''

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: example@gmail.com 
        from: example@gmail.com # Update your from mail id here
        smarthost: smtp.gmail.com:587
        auth_username: example@gmail.com # Update your from mail id here
        auth_identity: example@gmail.com # Update your from mail id here
        auth_password: password # Update your app-password here
        send_resolved: true
        headers:
          subject: " Prometheus -  Alert  "
        text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "
        # slack_configs:
        #  - channel: '@you'
        #    send_resolved: true

    route:
      group_wait: 10s
      group_interval: 2m
      receiver: 'gmail-notifications'
      repeat_interval: 2m
